using System;

// <autogenerated>
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// </autogenerated>
namespace BootstrapControls.Core.Fonts
{
	public sealed class Glyphicon : IFontIcon
	{
		private readonly string _value;

		private Glyphicon(string value)
        {
            _value = value;
        }

		public override String ToString()
        {
            return _value;
        }

		#region Constants
		
		public static readonly Glyphicon NONE = new Glyphicon(String.Empty);
		public static readonly Glyphicon ASTERISK = new Glyphicon("glyphicon glyphicon-asterisk");
		public static readonly Glyphicon PLUS = new Glyphicon("glyphicon glyphicon-plus");
		public static readonly Glyphicon EURO = new Glyphicon("glyphicon glyphicon-euro");
		public static readonly Glyphicon MINUS = new Glyphicon("glyphicon glyphicon-minus");
		public static readonly Glyphicon CLOUD = new Glyphicon("glyphicon glyphicon-cloud");
		public static readonly Glyphicon ENVELOPE = new Glyphicon("glyphicon glyphicon-envelope");
		public static readonly Glyphicon PENCIL = new Glyphicon("glyphicon glyphicon-pencil");
		public static readonly Glyphicon GLASS = new Glyphicon("glyphicon glyphicon-glass");
		public static readonly Glyphicon MUSIC = new Glyphicon("glyphicon glyphicon-music");
		public static readonly Glyphicon SEARCH = new Glyphicon("glyphicon glyphicon-search");
		public static readonly Glyphicon HEART = new Glyphicon("glyphicon glyphicon-heart");
		public static readonly Glyphicon STAR = new Glyphicon("glyphicon glyphicon-star");
		public static readonly Glyphicon STAR_EMPTY = new Glyphicon("glyphicon glyphicon-star-empty");
		public static readonly Glyphicon USER = new Glyphicon("glyphicon glyphicon-user");
		public static readonly Glyphicon FILM = new Glyphicon("glyphicon glyphicon-film");
		public static readonly Glyphicon TH_LARGE = new Glyphicon("glyphicon glyphicon-th-large");
		public static readonly Glyphicon TH = new Glyphicon("glyphicon glyphicon-th");
		public static readonly Glyphicon TH_LIST = new Glyphicon("glyphicon glyphicon-th-list");
		public static readonly Glyphicon OK = new Glyphicon("glyphicon glyphicon-ok");
		public static readonly Glyphicon REMOVE = new Glyphicon("glyphicon glyphicon-remove");
		public static readonly Glyphicon ZOOM_IN = new Glyphicon("glyphicon glyphicon-zoom-in");
		public static readonly Glyphicon ZOOM_OUT = new Glyphicon("glyphicon glyphicon-zoom-out");
		public static readonly Glyphicon OFF = new Glyphicon("glyphicon glyphicon-off");
		public static readonly Glyphicon SIGNAL = new Glyphicon("glyphicon glyphicon-signal");
		public static readonly Glyphicon COG = new Glyphicon("glyphicon glyphicon-cog");
		public static readonly Glyphicon TRASH = new Glyphicon("glyphicon glyphicon-trash");
		public static readonly Glyphicon HOME = new Glyphicon("glyphicon glyphicon-home");
		public static readonly Glyphicon FILE = new Glyphicon("glyphicon glyphicon-file");
		public static readonly Glyphicon TIME = new Glyphicon("glyphicon glyphicon-time");
		public static readonly Glyphicon ROAD = new Glyphicon("glyphicon glyphicon-road");
		public static readonly Glyphicon DOWNLOAD_ALT = new Glyphicon("glyphicon glyphicon-download-alt");
		public static readonly Glyphicon DOWNLOAD = new Glyphicon("glyphicon glyphicon-download");
		public static readonly Glyphicon UPLOAD = new Glyphicon("glyphicon glyphicon-upload");
		public static readonly Glyphicon INBOX = new Glyphicon("glyphicon glyphicon-inbox");
		public static readonly Glyphicon PLAY_CIRCLE = new Glyphicon("glyphicon glyphicon-play-circle");
		public static readonly Glyphicon REPEAT = new Glyphicon("glyphicon glyphicon-repeat");
		public static readonly Glyphicon REFRESH = new Glyphicon("glyphicon glyphicon-refresh");
		public static readonly Glyphicon LIST_ALT = new Glyphicon("glyphicon glyphicon-list-alt");
		public static readonly Glyphicon LOCK = new Glyphicon("glyphicon glyphicon-lock");
		public static readonly Glyphicon FLAG = new Glyphicon("glyphicon glyphicon-flag");
		public static readonly Glyphicon HEADPHONES = new Glyphicon("glyphicon glyphicon-headphones");
		public static readonly Glyphicon VOLUME_OFF = new Glyphicon("glyphicon glyphicon-volume-off");
		public static readonly Glyphicon VOLUME_DOWN = new Glyphicon("glyphicon glyphicon-volume-down");
		public static readonly Glyphicon VOLUME_UP = new Glyphicon("glyphicon glyphicon-volume-up");
		public static readonly Glyphicon QRCODE = new Glyphicon("glyphicon glyphicon-qrcode");
		public static readonly Glyphicon BARCODE = new Glyphicon("glyphicon glyphicon-barcode");
		public static readonly Glyphicon TAG = new Glyphicon("glyphicon glyphicon-tag");
		public static readonly Glyphicon TAGS = new Glyphicon("glyphicon glyphicon-tags");
		public static readonly Glyphicon BOOK = new Glyphicon("glyphicon glyphicon-book");
		public static readonly Glyphicon BOOKMARK = new Glyphicon("glyphicon glyphicon-bookmark");
		public static readonly Glyphicon PRINT = new Glyphicon("glyphicon glyphicon-print");
		public static readonly Glyphicon CAMERA = new Glyphicon("glyphicon glyphicon-camera");
		public static readonly Glyphicon FONT = new Glyphicon("glyphicon glyphicon-font");
		public static readonly Glyphicon BOLD = new Glyphicon("glyphicon glyphicon-bold");
		public static readonly Glyphicon ITALIC = new Glyphicon("glyphicon glyphicon-italic");
		public static readonly Glyphicon TEXT_HEIGHT = new Glyphicon("glyphicon glyphicon-text-height");
		public static readonly Glyphicon TEXT_WIDTH = new Glyphicon("glyphicon glyphicon-text-width");
		public static readonly Glyphicon ALIGN_LEFT = new Glyphicon("glyphicon glyphicon-align-left");
		public static readonly Glyphicon ALIGN_CENTER = new Glyphicon("glyphicon glyphicon-align-center");
		public static readonly Glyphicon ALIGN_RIGHT = new Glyphicon("glyphicon glyphicon-align-right");
		public static readonly Glyphicon ALIGN_JUSTIFY = new Glyphicon("glyphicon glyphicon-align-justify");
		public static readonly Glyphicon LIST = new Glyphicon("glyphicon glyphicon-list");
		public static readonly Glyphicon INDENT_LEFT = new Glyphicon("glyphicon glyphicon-indent-left");
		public static readonly Glyphicon INDENT_RIGHT = new Glyphicon("glyphicon glyphicon-indent-right");
		public static readonly Glyphicon FACETIME_VIDEO = new Glyphicon("glyphicon glyphicon-facetime-video");
		public static readonly Glyphicon PICTURE = new Glyphicon("glyphicon glyphicon-picture");
		public static readonly Glyphicon MAP_MARKER = new Glyphicon("glyphicon glyphicon-map-marker");
		public static readonly Glyphicon ADJUST = new Glyphicon("glyphicon glyphicon-adjust");
		public static readonly Glyphicon TINT = new Glyphicon("glyphicon glyphicon-tint");
		public static readonly Glyphicon EDIT = new Glyphicon("glyphicon glyphicon-edit");
		public static readonly Glyphicon SHARE = new Glyphicon("glyphicon glyphicon-share");
		public static readonly Glyphicon CHECK = new Glyphicon("glyphicon glyphicon-check");
		public static readonly Glyphicon MOVE = new Glyphicon("glyphicon glyphicon-move");
		public static readonly Glyphicon STEP_BACKWARD = new Glyphicon("glyphicon glyphicon-step-backward");
		public static readonly Glyphicon FAST_BACKWARD = new Glyphicon("glyphicon glyphicon-fast-backward");
		public static readonly Glyphicon BACKWARD = new Glyphicon("glyphicon glyphicon-backward");
		public static readonly Glyphicon PLAY = new Glyphicon("glyphicon glyphicon-play");
		public static readonly Glyphicon PAUSE = new Glyphicon("glyphicon glyphicon-pause");
		public static readonly Glyphicon STOP = new Glyphicon("glyphicon glyphicon-stop");
		public static readonly Glyphicon FORWARD = new Glyphicon("glyphicon glyphicon-forward");
		public static readonly Glyphicon FAST_FORWARD = new Glyphicon("glyphicon glyphicon-fast-forward");
		public static readonly Glyphicon STEP_FORWARD = new Glyphicon("glyphicon glyphicon-step-forward");
		public static readonly Glyphicon EJECT = new Glyphicon("glyphicon glyphicon-eject");
		public static readonly Glyphicon CHEVRON_LEFT = new Glyphicon("glyphicon glyphicon-chevron-left");
		public static readonly Glyphicon CHEVRON_RIGHT = new Glyphicon("glyphicon glyphicon-chevron-right");
		public static readonly Glyphicon PLUS_SIGN = new Glyphicon("glyphicon glyphicon-plus-sign");
		public static readonly Glyphicon MINUS_SIGN = new Glyphicon("glyphicon glyphicon-minus-sign");
		public static readonly Glyphicon REMOVE_SIGN = new Glyphicon("glyphicon glyphicon-remove-sign");
		public static readonly Glyphicon OK_SIGN = new Glyphicon("glyphicon glyphicon-ok-sign");
		public static readonly Glyphicon QUESTION_SIGN = new Glyphicon("glyphicon glyphicon-question-sign");
		public static readonly Glyphicon INFO_SIGN = new Glyphicon("glyphicon glyphicon-info-sign");
		public static readonly Glyphicon SCREENSHOT = new Glyphicon("glyphicon glyphicon-screenshot");
		public static readonly Glyphicon REMOVE_CIRCLE = new Glyphicon("glyphicon glyphicon-remove-circle");
		public static readonly Glyphicon OK_CIRCLE = new Glyphicon("glyphicon glyphicon-ok-circle");
		public static readonly Glyphicon BAN_CIRCLE = new Glyphicon("glyphicon glyphicon-ban-circle");
		public static readonly Glyphicon ARROW_LEFT = new Glyphicon("glyphicon glyphicon-arrow-left");
		public static readonly Glyphicon ARROW_RIGHT = new Glyphicon("glyphicon glyphicon-arrow-right");
		public static readonly Glyphicon ARROW_UP = new Glyphicon("glyphicon glyphicon-arrow-up");
		public static readonly Glyphicon ARROW_DOWN = new Glyphicon("glyphicon glyphicon-arrow-down");
		public static readonly Glyphicon SHARE_ALT = new Glyphicon("glyphicon glyphicon-share-alt");
		public static readonly Glyphicon RESIZE_FULL = new Glyphicon("glyphicon glyphicon-resize-full");
		public static readonly Glyphicon RESIZE_SMALL = new Glyphicon("glyphicon glyphicon-resize-small");
		public static readonly Glyphicon EXCLAMATION_SIGN = new Glyphicon("glyphicon glyphicon-exclamation-sign");
		public static readonly Glyphicon GIFT = new Glyphicon("glyphicon glyphicon-gift");
		public static readonly Glyphicon LEAF = new Glyphicon("glyphicon glyphicon-leaf");
		public static readonly Glyphicon FIRE = new Glyphicon("glyphicon glyphicon-fire");
		public static readonly Glyphicon EYE_OPEN = new Glyphicon("glyphicon glyphicon-eye-open");
		public static readonly Glyphicon EYE_CLOSE = new Glyphicon("glyphicon glyphicon-eye-close");
		public static readonly Glyphicon WARNING_SIGN = new Glyphicon("glyphicon glyphicon-warning-sign");
		public static readonly Glyphicon PLANE = new Glyphicon("glyphicon glyphicon-plane");
		public static readonly Glyphicon CALENDAR = new Glyphicon("glyphicon glyphicon-calendar");
		public static readonly Glyphicon RANDOM = new Glyphicon("glyphicon glyphicon-random");
		public static readonly Glyphicon COMMENT = new Glyphicon("glyphicon glyphicon-comment");
		public static readonly Glyphicon MAGNET = new Glyphicon("glyphicon glyphicon-magnet");
		public static readonly Glyphicon CHEVRON_UP = new Glyphicon("glyphicon glyphicon-chevron-up");
		public static readonly Glyphicon CHEVRON_DOWN = new Glyphicon("glyphicon glyphicon-chevron-down");
		public static readonly Glyphicon RETWEET = new Glyphicon("glyphicon glyphicon-retweet");
		public static readonly Glyphicon SHOPPING_CART = new Glyphicon("glyphicon glyphicon-shopping-cart");
		public static readonly Glyphicon FOLDER_CLOSE = new Glyphicon("glyphicon glyphicon-folder-close");
		public static readonly Glyphicon FOLDER_OPEN = new Glyphicon("glyphicon glyphicon-folder-open");
		public static readonly Glyphicon RESIZE_VERTICAL = new Glyphicon("glyphicon glyphicon-resize-vertical");
		public static readonly Glyphicon RESIZE_HORIZONTAL = new Glyphicon("glyphicon glyphicon-resize-horizontal");
		public static readonly Glyphicon HDD = new Glyphicon("glyphicon glyphicon-hdd");
		public static readonly Glyphicon BULLHORN = new Glyphicon("glyphicon glyphicon-bullhorn");
		public static readonly Glyphicon BELL = new Glyphicon("glyphicon glyphicon-bell");
		public static readonly Glyphicon CERTIFICATE = new Glyphicon("glyphicon glyphicon-certificate");
		public static readonly Glyphicon THUMBS_UP = new Glyphicon("glyphicon glyphicon-thumbs-up");
		public static readonly Glyphicon THUMBS_DOWN = new Glyphicon("glyphicon glyphicon-thumbs-down");
		public static readonly Glyphicon HAND_RIGHT = new Glyphicon("glyphicon glyphicon-hand-right");
		public static readonly Glyphicon HAND_LEFT = new Glyphicon("glyphicon glyphicon-hand-left");
		public static readonly Glyphicon HAND_UP = new Glyphicon("glyphicon glyphicon-hand-up");
		public static readonly Glyphicon HAND_DOWN = new Glyphicon("glyphicon glyphicon-hand-down");
		public static readonly Glyphicon CIRCLE_ARROW_RIGHT = new Glyphicon("glyphicon glyphicon-circle-arrow-right");
		public static readonly Glyphicon CIRCLE_ARROW_LEFT = new Glyphicon("glyphicon glyphicon-circle-arrow-left");
		public static readonly Glyphicon CIRCLE_ARROW_UP = new Glyphicon("glyphicon glyphicon-circle-arrow-up");
		public static readonly Glyphicon CIRCLE_ARROW_DOWN = new Glyphicon("glyphicon glyphicon-circle-arrow-down");
		public static readonly Glyphicon GLOBE = new Glyphicon("glyphicon glyphicon-globe");
		public static readonly Glyphicon WRENCH = new Glyphicon("glyphicon glyphicon-wrench");
		public static readonly Glyphicon TASKS = new Glyphicon("glyphicon glyphicon-tasks");
		public static readonly Glyphicon FILTER = new Glyphicon("glyphicon glyphicon-filter");
		public static readonly Glyphicon BRIEFCASE = new Glyphicon("glyphicon glyphicon-briefcase");
		public static readonly Glyphicon FULLSCREEN = new Glyphicon("glyphicon glyphicon-fullscreen");
		public static readonly Glyphicon DASHBOARD = new Glyphicon("glyphicon glyphicon-dashboard");
		public static readonly Glyphicon PAPERCLIP = new Glyphicon("glyphicon glyphicon-paperclip");
		public static readonly Glyphicon HEART_EMPTY = new Glyphicon("glyphicon glyphicon-heart-empty");
		public static readonly Glyphicon LINK = new Glyphicon("glyphicon glyphicon-link");
		public static readonly Glyphicon PHONE = new Glyphicon("glyphicon glyphicon-phone");
		public static readonly Glyphicon PUSHPIN = new Glyphicon("glyphicon glyphicon-pushpin");
		public static readonly Glyphicon USD = new Glyphicon("glyphicon glyphicon-usd");
		public static readonly Glyphicon GBP = new Glyphicon("glyphicon glyphicon-gbp");
		public static readonly Glyphicon SORT = new Glyphicon("glyphicon glyphicon-sort");
		public static readonly Glyphicon SORT_BY_ALPHABET = new Glyphicon("glyphicon glyphicon-sort-by-alphabet");
		public static readonly Glyphicon SORT_BY_ALPHABET_ALT = new Glyphicon("glyphicon glyphicon-sort-by-alphabet-alt");
		public static readonly Glyphicon SORT_BY_ORDER = new Glyphicon("glyphicon glyphicon-sort-by-order");
		public static readonly Glyphicon SORT_BY_ORDER_ALT = new Glyphicon("glyphicon glyphicon-sort-by-order-alt");
		public static readonly Glyphicon SORT_BY_ATTRIBUTES = new Glyphicon("glyphicon glyphicon-sort-by-attributes");
		public static readonly Glyphicon SORT_BY_ATTRIBUTES_ALT = new Glyphicon("glyphicon glyphicon-sort-by-attributes-alt");
		public static readonly Glyphicon UNCHECKED = new Glyphicon("glyphicon glyphicon-unchecked");
		public static readonly Glyphicon EXPAND = new Glyphicon("glyphicon glyphicon-expand");
		public static readonly Glyphicon COLLAPSE_DOWN = new Glyphicon("glyphicon glyphicon-collapse-down");
		public static readonly Glyphicon COLLAPSE_UP = new Glyphicon("glyphicon glyphicon-collapse-up");
		public static readonly Glyphicon LOG_IN = new Glyphicon("glyphicon glyphicon-log-in");
		public static readonly Glyphicon FLASH = new Glyphicon("glyphicon glyphicon-flash");
		public static readonly Glyphicon LOG_OUT = new Glyphicon("glyphicon glyphicon-log-out");
		public static readonly Glyphicon NEW_WINDOW = new Glyphicon("glyphicon glyphicon-new-window");
		public static readonly Glyphicon RECORD = new Glyphicon("glyphicon glyphicon-record");
		public static readonly Glyphicon SAVE = new Glyphicon("glyphicon glyphicon-save");
		public static readonly Glyphicon OPEN = new Glyphicon("glyphicon glyphicon-open");
		public static readonly Glyphicon SAVED = new Glyphicon("glyphicon glyphicon-saved");
		public static readonly Glyphicon IMPORT = new Glyphicon("glyphicon glyphicon-import");
		public static readonly Glyphicon EXPORT = new Glyphicon("glyphicon glyphicon-export");
		public static readonly Glyphicon SEND = new Glyphicon("glyphicon glyphicon-send");
		public static readonly Glyphicon FLOPPY_DISK = new Glyphicon("glyphicon glyphicon-floppy-disk");
		public static readonly Glyphicon FLOPPY_SAVED = new Glyphicon("glyphicon glyphicon-floppy-saved");
		public static readonly Glyphicon FLOPPY_REMOVE = new Glyphicon("glyphicon glyphicon-floppy-remove");
		public static readonly Glyphicon FLOPPY_SAVE = new Glyphicon("glyphicon glyphicon-floppy-save");
		public static readonly Glyphicon FLOPPY_OPEN = new Glyphicon("glyphicon glyphicon-floppy-open");
		public static readonly Glyphicon CREDIT_CARD = new Glyphicon("glyphicon glyphicon-credit-card");
		public static readonly Glyphicon TRANSFER = new Glyphicon("glyphicon glyphicon-transfer");
		public static readonly Glyphicon CUTLERY = new Glyphicon("glyphicon glyphicon-cutlery");
		public static readonly Glyphicon HEADER = new Glyphicon("glyphicon glyphicon-header");
		public static readonly Glyphicon COMPRESSED = new Glyphicon("glyphicon glyphicon-compressed");
		public static readonly Glyphicon EARPHONE = new Glyphicon("glyphicon glyphicon-earphone");
		public static readonly Glyphicon PHONE_ALT = new Glyphicon("glyphicon glyphicon-phone-alt");
		public static readonly Glyphicon TOWER = new Glyphicon("glyphicon glyphicon-tower");
		public static readonly Glyphicon STATS = new Glyphicon("glyphicon glyphicon-stats");
		public static readonly Glyphicon SD_VIDEO = new Glyphicon("glyphicon glyphicon-sd-video");
		public static readonly Glyphicon HD_VIDEO = new Glyphicon("glyphicon glyphicon-hd-video");
		public static readonly Glyphicon SUBTITLES = new Glyphicon("glyphicon glyphicon-subtitles");
		public static readonly Glyphicon SOUND_STEREO = new Glyphicon("glyphicon glyphicon-sound-stereo");
		public static readonly Glyphicon SOUND_DOLBY = new Glyphicon("glyphicon glyphicon-sound-dolby");
		public static readonly Glyphicon SOUND_5_1 = new Glyphicon("glyphicon glyphicon-sound-5-1");
		public static readonly Glyphicon SOUND_6_1 = new Glyphicon("glyphicon glyphicon-sound-6-1");
		public static readonly Glyphicon SOUND_7_1 = new Glyphicon("glyphicon glyphicon-sound-7-1");
		public static readonly Glyphicon COPYRIGHT_MARK = new Glyphicon("glyphicon glyphicon-copyright-mark");
		public static readonly Glyphicon REGISTRATION_MARK = new Glyphicon("glyphicon glyphicon-registration-mark");
		public static readonly Glyphicon CLOUD_DOWNLOAD = new Glyphicon("glyphicon glyphicon-cloud-download");
		public static readonly Glyphicon CLOUD_UPLOAD = new Glyphicon("glyphicon glyphicon-cloud-upload");
		public static readonly Glyphicon TREE_CONIFER = new Glyphicon("glyphicon glyphicon-tree-conifer");
		public static readonly Glyphicon TREE_DECIDUOUS = new Glyphicon("glyphicon glyphicon-tree-deciduous");

		#endregion
	}
}