
// <autogenerated>
// This code was generated by a tool. Any changes made manually will be lost
// the next time this code is regenerated.
// </autogenerated>
namespace BootstrapControls.Core
{
	public class GlyphiconConstants {
				
	  	  public const string ASTERISK = "glyphicon glyphicon-asterisk";
	
	  	  public const string PLUS = "glyphicon glyphicon-plus";
	
	  	  public const string EURO = "glyphicon glyphicon-euro";
	
	  	  public const string MINUS = "glyphicon glyphicon-minus";
	
	  	  public const string CLOUD = "glyphicon glyphicon-cloud";
	
	  	  public const string ENVELOPE = "glyphicon glyphicon-envelope";
	
	  	  public const string PENCIL = "glyphicon glyphicon-pencil";
	
	  	  public const string GLASS = "glyphicon glyphicon-glass";
	
	  	  public const string MUSIC = "glyphicon glyphicon-music";
	
	  	  public const string SEARCH = "glyphicon glyphicon-search";
	
	  	  public const string HEART = "glyphicon glyphicon-heart";
	
	  	  public const string STAR = "glyphicon glyphicon-star";
	
	  	  public const string STAR_EMPTY = "glyphicon glyphicon-star-empty";
	
	  	  public const string USER = "glyphicon glyphicon-user";
	
	  	  public const string FILM = "glyphicon glyphicon-film";
	
	  	  public const string TH_LARGE = "glyphicon glyphicon-th-large";
	
	  	  public const string TH = "glyphicon glyphicon-th";
	
	  	  public const string TH_LIST = "glyphicon glyphicon-th-list";
	
	  	  public const string OK = "glyphicon glyphicon-ok";
	
	  	  public const string REMOVE = "glyphicon glyphicon-remove";
	
	  	  public const string ZOOM_IN = "glyphicon glyphicon-zoom-in";
	
	  	  public const string ZOOM_OUT = "glyphicon glyphicon-zoom-out";
	
	  	  public const string OFF = "glyphicon glyphicon-off";
	
	  	  public const string SIGNAL = "glyphicon glyphicon-signal";
	
	  	  public const string COG = "glyphicon glyphicon-cog";
	
	  	  public const string TRASH = "glyphicon glyphicon-trash";
	
	  	  public const string HOME = "glyphicon glyphicon-home";
	
	  	  public const string FILE = "glyphicon glyphicon-file";
	
	  	  public const string TIME = "glyphicon glyphicon-time";
	
	  	  public const string ROAD = "glyphicon glyphicon-road";
	
	  	  public const string DOWNLOAD_ALT = "glyphicon glyphicon-download-alt";
	
	  	  public const string DOWNLOAD = "glyphicon glyphicon-download";
	
	  	  public const string UPLOAD = "glyphicon glyphicon-upload";
	
	  	  public const string INBOX = "glyphicon glyphicon-inbox";
	
	  	  public const string PLAY_CIRCLE = "glyphicon glyphicon-play-circle";
	
	  	  public const string REPEAT = "glyphicon glyphicon-repeat";
	
	  	  public const string REFRESH = "glyphicon glyphicon-refresh";
	
	  	  public const string LIST_ALT = "glyphicon glyphicon-list-alt";
	
	  	  public const string LOCK = "glyphicon glyphicon-lock";
	
	  	  public const string FLAG = "glyphicon glyphicon-flag";
	
	  	  public const string HEADPHONES = "glyphicon glyphicon-headphones";
	
	  	  public const string VOLUME_OFF = "glyphicon glyphicon-volume-off";
	
	  	  public const string VOLUME_DOWN = "glyphicon glyphicon-volume-down";
	
	  	  public const string VOLUME_UP = "glyphicon glyphicon-volume-up";
	
	  	  public const string QRCODE = "glyphicon glyphicon-qrcode";
	
	  	  public const string BARCODE = "glyphicon glyphicon-barcode";
	
	  	  public const string TAG = "glyphicon glyphicon-tag";
	
	  	  public const string TAGS = "glyphicon glyphicon-tags";
	
	  	  public const string BOOK = "glyphicon glyphicon-book";
	
	  	  public const string BOOKMARK = "glyphicon glyphicon-bookmark";
	
	  	  public const string PRINT = "glyphicon glyphicon-print";
	
	  	  public const string CAMERA = "glyphicon glyphicon-camera";
	
	  	  public const string FONT = "glyphicon glyphicon-font";
	
	  	  public const string BOLD = "glyphicon glyphicon-bold";
	
	  	  public const string ITALIC = "glyphicon glyphicon-italic";
	
	  	  public const string TEXT_HEIGHT = "glyphicon glyphicon-text-height";
	
	  	  public const string TEXT_WIDTH = "glyphicon glyphicon-text-width";
	
	  	  public const string ALIGN_LEFT = "glyphicon glyphicon-align-left";
	
	  	  public const string ALIGN_CENTER = "glyphicon glyphicon-align-center";
	
	  	  public const string ALIGN_RIGHT = "glyphicon glyphicon-align-right";
	
	  	  public const string ALIGN_JUSTIFY = "glyphicon glyphicon-align-justify";
	
	  	  public const string LIST = "glyphicon glyphicon-list";
	
	  	  public const string INDENT_LEFT = "glyphicon glyphicon-indent-left";
	
	  	  public const string INDENT_RIGHT = "glyphicon glyphicon-indent-right";
	
	  	  public const string FACETIME_VIDEO = "glyphicon glyphicon-facetime-video";
	
	  	  public const string PICTURE = "glyphicon glyphicon-picture";
	
	  	  public const string MAP_MARKER = "glyphicon glyphicon-map-marker";
	
	  	  public const string ADJUST = "glyphicon glyphicon-adjust";
	
	  	  public const string TINT = "glyphicon glyphicon-tint";
	
	  	  public const string EDIT = "glyphicon glyphicon-edit";
	
	  	  public const string SHARE = "glyphicon glyphicon-share";
	
	  	  public const string CHECK = "glyphicon glyphicon-check";
	
	  	  public const string MOVE = "glyphicon glyphicon-move";
	
	  	  public const string STEP_BACKWARD = "glyphicon glyphicon-step-backward";
	
	  	  public const string FAST_BACKWARD = "glyphicon glyphicon-fast-backward";
	
	  	  public const string BACKWARD = "glyphicon glyphicon-backward";
	
	  	  public const string PLAY = "glyphicon glyphicon-play";
	
	  	  public const string PAUSE = "glyphicon glyphicon-pause";
	
	  	  public const string STOP = "glyphicon glyphicon-stop";
	
	  	  public const string FORWARD = "glyphicon glyphicon-forward";
	
	  	  public const string FAST_FORWARD = "glyphicon glyphicon-fast-forward";
	
	  	  public const string STEP_FORWARD = "glyphicon glyphicon-step-forward";
	
	  	  public const string EJECT = "glyphicon glyphicon-eject";
	
	  	  public const string CHEVRON_LEFT = "glyphicon glyphicon-chevron-left";
	
	  	  public const string CHEVRON_RIGHT = "glyphicon glyphicon-chevron-right";
	
	  	  public const string PLUS_SIGN = "glyphicon glyphicon-plus-sign";
	
	  	  public const string MINUS_SIGN = "glyphicon glyphicon-minus-sign";
	
	  	  public const string REMOVE_SIGN = "glyphicon glyphicon-remove-sign";
	
	  	  public const string OK_SIGN = "glyphicon glyphicon-ok-sign";
	
	  	  public const string QUESTION_SIGN = "glyphicon glyphicon-question-sign";
	
	  	  public const string INFO_SIGN = "glyphicon glyphicon-info-sign";
	
	  	  public const string SCREENSHOT = "glyphicon glyphicon-screenshot";
	
	  	  public const string REMOVE_CIRCLE = "glyphicon glyphicon-remove-circle";
	
	  	  public const string OK_CIRCLE = "glyphicon glyphicon-ok-circle";
	
	  	  public const string BAN_CIRCLE = "glyphicon glyphicon-ban-circle";
	
	  	  public const string ARROW_LEFT = "glyphicon glyphicon-arrow-left";
	
	  	  public const string ARROW_RIGHT = "glyphicon glyphicon-arrow-right";
	
	  	  public const string ARROW_UP = "glyphicon glyphicon-arrow-up";
	
	  	  public const string ARROW_DOWN = "glyphicon glyphicon-arrow-down";
	
	  	  public const string SHARE_ALT = "glyphicon glyphicon-share-alt";
	
	  	  public const string RESIZE_FULL = "glyphicon glyphicon-resize-full";
	
	  	  public const string RESIZE_SMALL = "glyphicon glyphicon-resize-small";
	
	  	  public const string EXCLAMATION_SIGN = "glyphicon glyphicon-exclamation-sign";
	
	  	  public const string GIFT = "glyphicon glyphicon-gift";
	
	  	  public const string LEAF = "glyphicon glyphicon-leaf";
	
	  	  public const string FIRE = "glyphicon glyphicon-fire";
	
	  	  public const string EYE_OPEN = "glyphicon glyphicon-eye-open";
	
	  	  public const string EYE_CLOSE = "glyphicon glyphicon-eye-close";
	
	  	  public const string WARNING_SIGN = "glyphicon glyphicon-warning-sign";
	
	  	  public const string PLANE = "glyphicon glyphicon-plane";
	
	  	  public const string CALENDAR = "glyphicon glyphicon-calendar";
	
	  	  public const string RANDOM = "glyphicon glyphicon-random";
	
	  	  public const string COMMENT = "glyphicon glyphicon-comment";
	
	  	  public const string MAGNET = "glyphicon glyphicon-magnet";
	
	  	  public const string CHEVRON_UP = "glyphicon glyphicon-chevron-up";
	
	  	  public const string CHEVRON_DOWN = "glyphicon glyphicon-chevron-down";
	
	  	  public const string RETWEET = "glyphicon glyphicon-retweet";
	
	  	  public const string SHOPPING_CART = "glyphicon glyphicon-shopping-cart";
	
	  	  public const string FOLDER_CLOSE = "glyphicon glyphicon-folder-close";
	
	  	  public const string FOLDER_OPEN = "glyphicon glyphicon-folder-open";
	
	  	  public const string RESIZE_VERTICAL = "glyphicon glyphicon-resize-vertical";
	
	  	  public const string RESIZE_HORIZONTAL = "glyphicon glyphicon-resize-horizontal";
	
	  	  public const string HDD = "glyphicon glyphicon-hdd";
	
	  	  public const string BULLHORN = "glyphicon glyphicon-bullhorn";
	
	  	  public const string BELL = "glyphicon glyphicon-bell";
	
	  	  public const string CERTIFICATE = "glyphicon glyphicon-certificate";
	
	  	  public const string THUMBS_UP = "glyphicon glyphicon-thumbs-up";
	
	  	  public const string THUMBS_DOWN = "glyphicon glyphicon-thumbs-down";
	
	  	  public const string HAND_RIGHT = "glyphicon glyphicon-hand-right";
	
	  	  public const string HAND_LEFT = "glyphicon glyphicon-hand-left";
	
	  	  public const string HAND_UP = "glyphicon glyphicon-hand-up";
	
	  	  public const string HAND_DOWN = "glyphicon glyphicon-hand-down";
	
	  	  public const string CIRCLE_ARROW_RIGHT = "glyphicon glyphicon-circle-arrow-right";
	
	  	  public const string CIRCLE_ARROW_LEFT = "glyphicon glyphicon-circle-arrow-left";
	
	  	  public const string CIRCLE_ARROW_UP = "glyphicon glyphicon-circle-arrow-up";
	
	  	  public const string CIRCLE_ARROW_DOWN = "glyphicon glyphicon-circle-arrow-down";
	
	  	  public const string GLOBE = "glyphicon glyphicon-globe";
	
	  	  public const string WRENCH = "glyphicon glyphicon-wrench";
	
	  	  public const string TASKS = "glyphicon glyphicon-tasks";
	
	  	  public const string FILTER = "glyphicon glyphicon-filter";
	
	  	  public const string BRIEFCASE = "glyphicon glyphicon-briefcase";
	
	  	  public const string FULLSCREEN = "glyphicon glyphicon-fullscreen";
	
	  	  public const string DASHBOARD = "glyphicon glyphicon-dashboard";
	
	  	  public const string PAPERCLIP = "glyphicon glyphicon-paperclip";
	
	  	  public const string HEART_EMPTY = "glyphicon glyphicon-heart-empty";
	
	  	  public const string LINK = "glyphicon glyphicon-link";
	
	  	  public const string PHONE = "glyphicon glyphicon-phone";
	
	  	  public const string PUSHPIN = "glyphicon glyphicon-pushpin";
	
	  	  public const string USD = "glyphicon glyphicon-usd";
	
	  	  public const string GBP = "glyphicon glyphicon-gbp";
	
	  	  public const string SORT = "glyphicon glyphicon-sort";
	
	  	  public const string SORT_BY_ALPHABET = "glyphicon glyphicon-sort-by-alphabet";
	
	  	  public const string SORT_BY_ALPHABET_ALT = "glyphicon glyphicon-sort-by-alphabet-alt";
	
	  	  public const string SORT_BY_ORDER = "glyphicon glyphicon-sort-by-order";
	
	  	  public const string SORT_BY_ORDER_ALT = "glyphicon glyphicon-sort-by-order-alt";
	
	  	  public const string SORT_BY_ATTRIBUTES = "glyphicon glyphicon-sort-by-attributes";
	
	  	  public const string SORT_BY_ATTRIBUTES_ALT = "glyphicon glyphicon-sort-by-attributes-alt";
	
	  	  public const string UNCHECKED = "glyphicon glyphicon-unchecked";
	
	  	  public const string EXPAND = "glyphicon glyphicon-expand";
	
	  	  public const string COLLAPSE_DOWN = "glyphicon glyphicon-collapse-down";
	
	  	  public const string COLLAPSE_UP = "glyphicon glyphicon-collapse-up";
	
	  	  public const string LOG_IN = "glyphicon glyphicon-log-in";
	
	  	  public const string FLASH = "glyphicon glyphicon-flash";
	
	  	  public const string LOG_OUT = "glyphicon glyphicon-log-out";
	
	  	  public const string NEW_WINDOW = "glyphicon glyphicon-new-window";
	
	  	  public const string RECORD = "glyphicon glyphicon-record";
	
	  	  public const string SAVE = "glyphicon glyphicon-save";
	
	  	  public const string OPEN = "glyphicon glyphicon-open";
	
	  	  public const string SAVED = "glyphicon glyphicon-saved";
	
	  	  public const string IMPORT = "glyphicon glyphicon-import";
	
	  	  public const string EXPORT = "glyphicon glyphicon-export";
	
	  	  public const string SEND = "glyphicon glyphicon-send";
	
	  	  public const string FLOPPY_DISK = "glyphicon glyphicon-floppy-disk";
	
	  	  public const string FLOPPY_SAVED = "glyphicon glyphicon-floppy-saved";
	
	  	  public const string FLOPPY_REMOVE = "glyphicon glyphicon-floppy-remove";
	
	  	  public const string FLOPPY_SAVE = "glyphicon glyphicon-floppy-save";
	
	  	  public const string FLOPPY_OPEN = "glyphicon glyphicon-floppy-open";
	
	  	  public const string CREDIT_CARD = "glyphicon glyphicon-credit-card";
	
	  	  public const string TRANSFER = "glyphicon glyphicon-transfer";
	
	  	  public const string CUTLERY = "glyphicon glyphicon-cutlery";
	
	  	  public const string HEADER = "glyphicon glyphicon-header";
	
	  	  public const string COMPRESSED = "glyphicon glyphicon-compressed";
	
	  	  public const string EARPHONE = "glyphicon glyphicon-earphone";
	
	  	  public const string PHONE_ALT = "glyphicon glyphicon-phone-alt";
	
	  	  public const string TOWER = "glyphicon glyphicon-tower";
	
	  	  public const string STATS = "glyphicon glyphicon-stats";
	
	  	  public const string SD_VIDEO = "glyphicon glyphicon-sd-video";
	
	  	  public const string HD_VIDEO = "glyphicon glyphicon-hd-video";
	
	  	  public const string SUBTITLES = "glyphicon glyphicon-subtitles";
	
	  	  public const string SOUND_STEREO = "glyphicon glyphicon-sound-stereo";
	
	  	  public const string SOUND_DOLBY = "glyphicon glyphicon-sound-dolby";
	
	  	  public const string SOUND_5_1 = "glyphicon glyphicon-sound-5-1";
	
	  	  public const string SOUND_6_1 = "glyphicon glyphicon-sound-6-1";
	
	  	  public const string SOUND_7_1 = "glyphicon glyphicon-sound-7-1";
	
	  	  public const string COPYRIGHT_MARK = "glyphicon glyphicon-copyright-mark";
	
	  	  public const string REGISTRATION_MARK = "glyphicon glyphicon-registration-mark";
	
	  	  public const string CLOUD_DOWNLOAD = "glyphicon glyphicon-cloud-download";
	
	  	  public const string CLOUD_UPLOAD = "glyphicon glyphicon-cloud-upload";
	
	  	  public const string TREE_CONIFER = "glyphicon glyphicon-tree-conifer";
	
	  	  public const string TREE_DECIDUOUS = "glyphicon glyphicon-tree-deciduous";
		}
}